name = "Jieba"
uuid = "b39fac2a-be77-446b-973f-d409bcc802d5"
authors = ["bowaer <cb229435444@outlook.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
